name: Build module with the latest classmaps from github.com/spicetify/classmaps

on:
   schedule:
      - cron: "11 9 * * *"

permissions:
   contents: write

jobs:
   auto-build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Install Node v22
           uses: actions/setup-node@v1
           with:
              node-version: 22
         - name: Prepare environment
           run: npm i
         - name: Build
           run: |
              npm run cron module
              mkdir dist
              for DIR in module/dist/*; do
                pushd $DIR
                ARCHIVE="$(basename "$DIR").zip"
                7z a -bb0 -sdel "$ARCHIVE" ./*
                mv "$ARCHIVE" $HOME/
                popd
              done
         - name: Release
           id: release
           uses: softprops/action-gh-release@v2
           with:
              files: dist/*
         - name: Update repo.json
           run: |
              for URL in ${{ fromJSON(steps.release.outputs.assets).*.browser_download_url }}; do
                ARCHIVE="${URL##*/}"
                IFS="@" read -r ID VERSION <<< "$ARCHIVE"
                IFS="." read -r -a IDS <<< "$ID"
                ID="$(printf '["%s"]' "${IDS[@]}")"
                VERSION="${ARCHIVE%.zip}"
                yq -i ".${ID}.v[\"${VERSION/?}\"].artifacts += [\"${URL}\"]" repo.json
              done
